coverage:
  if: true
  acceptable: 80%
  badge:
    path: docs/coverage.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
codeToTestRatio:
  codeToTestRatio:
    code:
      - '**/*.go'
      - '!**/*_test.go'
    test:
      - '**/*_test.go'
  badge:
    path: docs/ratio.svg
testExecutionTime:
  badge:
    path: docs/time.svg