name: Coverage

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1"
          check-latest: true

      - name: Dependencies
        run: make get

      - name: Run tests with coverage report output
        run: make coverage

      - uses: k1LoW/octocov-action@v1